// 3-Layer Permission System: Page, Feature, Action
export const PERMISSION_LAYERS = {
  PAGE: 'PAGE',
  FEATURE: 'FEATURE',
  ACTION: 'ACTION'
};

export const PERMISSION_DEFINITIONS = [
  // LAYER 1: PAGE ACCESS
  { key: 'page.dashboard', label: 'Overview / Dashboard', layer: PERMISSION_LAYERS.PAGE, group: 'Pages', description: 'Access tenant overview and operational metrics' },
  { key: 'page.members', label: 'Members Page', layer: PERMISSION_LAYERS.PAGE, group: 'Pages', description: 'Access members roster and profiles' },
  { key: 'page.leads', label: 'CRM & Leads Page', layer: PERMISSION_LAYERS.PAGE, group: 'Pages', description: 'Access sales pipeline and trial leads' },
  { key: 'page.classes', label: 'Classes Page', layer: PERMISSION_LAYERS.PAGE, group: 'Pages', description: 'Access class schedule and bookings' },
  { key: 'page.trainers', label: 'Trainers Page', layer: PERMISSION_LAYERS.PAGE, group: 'Pages', description: 'Access trainer roster and availability' },
  { key: 'page.payments', label: 'Payments & Billing', layer: PERMISSION_LAYERS.PAGE, group: 'Pages', description: 'Access invoices and billing transactions' },
  { key: 'page.attendance', label: 'Attendance & Check-in', layer: PERMISSION_LAYERS.PAGE, group: 'Pages', description: 'Access check-in scanner and attendance logs' },
  { key: 'page.analytics', label: 'Analytics & Reports', layer: PERMISSION_LAYERS.PAGE, group: 'Pages', description: 'Access business performance and retention analytics' },
  { key: 'page.retention', label: 'Retention Engine', layer: PERMISSION_LAYERS.PAGE, group: 'Pages', description: 'Access churn risk alerts and re-engagement tools' },
  { key: 'page.ai', label: 'Owner AI Insights', layer: PERMISSION_LAYERS.PAGE, group: 'Pages', description: 'Access contextual business intelligence assistant' },
  { key: 'page.settings', label: 'Tenant Settings', layer: PERMISSION_LAYERS.PAGE, group: 'Pages', description: 'Configure gym hours, details, and preferences' },

  // LAYER 2: FEATURE VISIBILITY (INSIDE PAGES)
  { key: 'member.viewPayments', label: 'View Member Payments', layer: PERMISSION_LAYERS.FEATURE, group: 'Member Features', description: 'View financial history on member profiles' },
  { key: 'member.viewProgress', label: 'View Fitness Progress', layer: PERMISSION_LAYERS.FEATURE, group: 'Member Features', description: 'View member weight and body measurement logs' },
  { key: 'member.viewNotes', label: 'View Member Notes', layer: PERMISSION_LAYERS.FEATURE, group: 'Member Features', description: 'View confidential staff notes on members' },
  { key: 'member.viewWorkout', label: 'View Member Workouts', layer: PERMISSION_LAYERS.FEATURE, group: 'Member Features', description: 'View exercise histories and personal records' },
  { key: 'lead.viewContactInfo', label: 'View Lead Contacts', layer: PERMISSION_LAYERS.FEATURE, group: 'CRM Features', description: 'View customer phone numbers and email addresses' },
  { key: 'lead.viewNotes', label: 'View Lead Notes', layer: PERMISSION_LAYERS.FEATURE, group: 'CRM Features', description: 'View communication logs and follow-up history' },
  { key: 'class.viewRoster', label: 'View Class Roster', layer: PERMISSION_LAYERS.FEATURE, group: 'Class Features', description: 'See names of all booked attendees' },
  { key: 'payment.viewRevenueSummary', label: 'View Revenue Totals', layer: PERMISSION_LAYERS.FEATURE, group: 'Financial Features', description: 'View aggregate revenue numbers, MRR, and cash flow' },
  { key: 'attendance.viewLiveFeed', label: 'View Live Check-in Feed', layer: PERMISSION_LAYERS.FEATURE, group: 'Attendance Features', description: 'Real-time check-in stream updates' },
  { key: 'ai.businessInsights', label: 'Strategic AI Insights', layer: PERMISSION_LAYERS.FEATURE, group: 'AI Features', description: 'Generate executive summaries and revenue tips' },
  { key: 'ai.generateMessages', label: 'AI Follow-up Generator', layer: PERMISSION_LAYERS.FEATURE, group: 'AI Features', description: 'Draft automated personalized re-engagement messages' },

  // LAYER 3: ACTION PERMISSIONS
  { key: 'member.create', label: 'Create Member', layer: PERMISSION_LAYERS.ACTION, group: 'Member Actions', description: 'Enroll a new gym member' },
  { key: 'member.edit', label: 'Edit Member Profile', layer: PERMISSION_LAYERS.ACTION, group: 'Member Actions', description: 'Modify member contact, plan, or medical details' },
  { key: 'member.archive', label: 'Archive / Deactivate', layer: PERMISSION_LAYERS.ACTION, group: 'Member Actions', description: 'Deactivate or cancel member accounts' },
  { key: 'member.assignTrainer', label: 'Assign Trainer', layer: PERMISSION_LAYERS.ACTION, group: 'Member Actions', description: 'Assign personal trainer to a member' },
  { key: 'member.export', label: 'Export Member Roster', layer: PERMISSION_LAYERS.ACTION, group: 'Member Actions', description: 'Export member contact data as CSV' },
  { key: 'lead.create', label: 'Add Lead Manually', layer: PERMISSION_LAYERS.ACTION, group: 'CRM Actions', description: 'Create walk-in or manual sales lead' },
  { key: 'lead.editStatus', label: 'Move Lead Stage', layer: PERMISSION_LAYERS.ACTION, group: 'CRM Actions', description: 'Change lead status across pipeline columns' },
  { key: 'lead.convert', label: 'Convert Lead to Member', layer: PERMISSION_LAYERS.ACTION, group: 'CRM Actions', description: '1-click convert qualified lead into active member' },
  { key: 'class.create', label: 'Create New Class', layer: PERMISSION_LAYERS.ACTION, group: 'Class Actions', description: 'Schedule new group fitness sessions' },
  { key: 'class.cancel', label: 'Cancel Class', layer: PERMISSION_LAYERS.ACTION, group: 'Class Actions', description: 'Cancel class and notify booked members' },
  { key: 'attendance.markManual', label: 'Manual Check-in Override', layer: PERMISSION_LAYERS.ACTION, group: 'Attendance Actions', description: 'Manually check in member without QR' },
  { key: 'attendance.scanQR', label: 'Scan Digital QR Pass', layer: PERMISSION_LAYERS.ACTION, group: 'Attendance Actions', description: 'Operate front desk QR scanner simulator' },
  { key: 'payment.create', label: 'Record New Payment', layer: PERMISSION_LAYERS.ACTION, group: 'Financial Actions', description: 'Record UPI, Card, Cash, or Transfer payment' },
  { key: 'payment.refund', label: 'Process Refund', layer: PERMISSION_LAYERS.ACTION, group: 'Financial Actions', description: 'Issue refund for previously collected fees' },
  { key: 'retention.triggerOutreach', label: 'Trigger Retention Outreach', layer: PERMISSION_LAYERS.ACTION, group: 'Retention Actions', description: 'Send follow-up messages to at-risk members' }
];

// Default baseline permissions matrix by role key
export const DEFAULT_ROLE_PERMISSIONS = {
  super_admin: PERMISSION_DEFINITIONS.reduce((acc, p) => ({ ...acc, [p.key]: true }), {}),
  
  owner: PERMISSION_DEFINITIONS.reduce((acc, p) => ({ ...acc, [p.key]: true }), {}),

  manager: {
    'page.dashboard': true,
    'page.members': true,
    'page.leads': true,
    'page.classes': true,
    'page.trainers': true,
    'page.payments': true,
    'page.attendance': true,
    'page.analytics': true,
    'page.retention': true,
    'page.ai': true,
    'page.settings': false,
    'member.viewPayments': true,
    'member.viewProgress': true,
    'member.viewNotes': true,
    'member.viewWorkout': true,
    'lead.viewContactInfo': true,
    'lead.viewNotes': true,
    'class.viewRoster': true,
    'payment.viewRevenueSummary': true,
    'attendance.viewLiveFeed': true,
    'ai.businessInsights': true,
    'ai.generateMessages': true,
    'member.create': true,
    'member.edit': true,
    'member.archive': false,
    'member.assignTrainer': true,
    'member.export': true,
    'lead.create': true,
    'lead.editStatus': true,
    'lead.convert': true,
    'class.create': true,
    'class.cancel': true,
    'attendance.markManual': true,
    'attendance.scanQR': true,
    'payment.create': true,
    'payment.refund': false,
    'retention.triggerOutreach': true
  },

  trainer: {
    'page.dashboard': true,
    'page.members': true,
    'page.leads': false,
    'page.classes': true,
    'page.trainers': false,
    'page.payments': false, // NO billing by default
    'page.attendance': true,
    'page.analytics': false, // NO analytics by default (overridable per user)
    'page.retention': false,
    'page.ai': false,
    'page.settings': false,
    'member.viewPayments': false,
    'member.viewProgress': true,
    'member.viewNotes': true,
    'member.viewWorkout': true,
    'lead.viewContactInfo': false,
    'lead.viewNotes': false,
    'class.viewRoster': true,
    'payment.viewRevenueSummary': false,
    'attendance.viewLiveFeed': true,
    'ai.businessInsights': false,
    'ai.generateMessages': false,
    'member.create': false,
    'member.edit': false,
    'member.archive': false,
    'member.assignTrainer': false,
    'member.export': false,
    'lead.create': false,
    'lead.editStatus': false,
    'lead.convert': false,
    'class.create': false,
    'class.cancel': false,
    'attendance.markManual': true,
    'attendance.scanQR': false,
    'payment.create': false,
    'payment.refund': false,
    'retention.triggerOutreach': false
  },

  receptionist: {
    'page.dashboard': true,
    'page.members': true,
    'page.leads': true,
    'page.classes': true,
    'page.trainers': false,
    'page.payments': true, // Can view payments
    'page.attendance': true,
    'page.analytics': false,
    'page.retention': false,
    'page.ai': false,
    'page.settings': false,
    'member.viewPayments': true,
    'member.viewProgress': false,
    'member.viewNotes': false,
    'member.viewWorkout': false,
    'lead.viewContactInfo': true,
    'lead.viewNotes': true,
    'class.viewRoster': true,
    'payment.viewRevenueSummary': false,
    'attendance.viewLiveFeed': true,
    'ai.businessInsights': false,
    'ai.generateMessages': false,
    'member.create': true,
    'member.edit': true,
    'member.archive': false,
    'member.assignTrainer': false,
    'member.export': false,
    'lead.create': true,
    'lead.editStatus': true,
    'lead.convert': true,
    'class.create': false,
    'class.cancel': false,
    'attendance.markManual': true,
    'attendance.scanQR': true,
    'payment.create': true,
    'payment.refund': false,
    'retention.triggerOutreach': false
  },

  member: {
    'page.dashboard': true,
    'page.members': false,
    'page.leads': false,
    'page.classes': true,
    'page.trainers': false,
    'page.payments': false,
    'page.attendance': true,
    'page.analytics': false,
    'page.retention': false,
    'page.ai': false,
    'page.settings': false,
    'member.viewPayments': false,
    'member.viewProgress': true,
    'member.viewNotes': false,
    'member.viewWorkout': true,
    'lead.viewContactInfo': false,
    'lead.viewNotes': false,
    'class.viewRoster': false,
    'payment.viewRevenueSummary': false,
    'attendance.viewLiveFeed': false,
    'ai.businessInsights': false,
    'ai.generateMessages': false,
    'member.create': false,
    'member.edit': false,
    'member.archive': false,
    'member.assignTrainer': false,
    'member.export': false,
    'lead.create': false,
    'lead.editStatus': false,
    'lead.convert': false,
    'class.create': false,
    'class.cancel': false,
    'attendance.markManual': false,
    'attendance.scanQR': false,
    'payment.create': false,
    'payment.refund': false,
    'retention.triggerOutreach': false
  }
};
